sudo: false

cache:
  directories:
    - $HOME/env

language: python

notifications:
  email: false

matrix:
  include:
    - python: 3.5
    - python: 3.6

before_install:
  - bash .travis_dependencies.sh
  - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
  - hash -r
  - source activate test-environment
  - conda list

install:
  # install your own package into the environment
  # pip install -e rather than setup.py, so that coverage can find the source
  - pip install -e .[tests]
  - pip install coverage>=4.4 --upgrade


script:
  - py.test

after_success:
  - coveralls
  - pip uninstall -y norbert

after_failure:
  - pip uninstall -y norbert
